exclude: "^tests/test_rules/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/reorder_python_imports
    rev: "v3.12.0"
    hooks:
      - id: reorder-python-imports
        args:
          - "--py38-plus"
  - repo: https://github.com/psf/black
    rev: "23.12.1"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        entry: prettier --write
        files: \.(yaml|yml|md)$
