name: Routes CI
on: [push, pull_request]
jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # https://github.com/actions/setup-python/issues/850
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Run CI
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install --with dev
          poetry run pytest --cov
          poetry run semgrep --test --config routes/rules/ tests/test_rules/
